name: build foss snapshot
on:
  workflow_dispatch:
  workflow_call:          
  
jobs:
  call-image-builder-foss-snapshot:
    permissions:
      contents: write
    uses:
      ./.github/workflows/_image_builder.yml
    with:
      build_settings: 
        '{"SOURCE_REPO":  "https://github.com/openwrt/openwrt.git", 
        "SOURCE_BRANCH": "main",
        "BUILD_REPO":    "https://github.com/${{github.repository}}.git",
        "BUILD_BRANCH": "build",
        "BUILD_INIT": "init_build.sh",
        "BUILD_TYPE":  "foss",
        "BUILD_VER": "snapshot",
        "BUILD_TAG": "",
        "BUILD_SYNC": "y",        
        "BUILD_KMOD": "y"}'
