name: build foss 24.10
on:
  workflow_dispatch:
  workflow_call:

jobs:
  call-image-builder-foss-24_10:
    permissions:
      contents: write
    uses:
      ./.github/workflows/_image_builder.yml
    with:
      build_settings: 
        '{"SOURCE_REPO":  "https://github.com/openwrt/openwrt.git", 
        "SOURCE_BRANCH": "openwrt-24.10",
        "BUILD_REPO":    "https://github.com/${{github.repository}}.git",
        "BUILD_BRANCH": "build",
        "BUILD_INIT": "init_build.sh",
        "BUILD_TYPE":  "foss",
        "BUILD_VER": "24.10-SNAPSHOT",
        "BUILD_TAG": "",
        "BUILD_KMOD": "y"}'        